server:
  name: "chains-auth"
  port: ":8001"
  base_path: "/api/v1"
  test_mode: true
  log:
    level: "debug"
    format: "text"

database:
  sql:
    url: "postgresql://postgres:postgres@db:7000/postgres?sslmode=disable"

oauth:
  google:
    client_id: "client_id"
    client_secret: "megasupersecret"
    redirect_url: "http://localhost:8001/re-flow/v1/public/oauth/google/callback"

jwt:
  access_token:
    secret_key: "supersecretkey"
    token_lifetime: 900
  refresh_token:
    secret_key: "refreshsuperkey"
    encryption_key: "f6tD7wVYNvXMm4MwqivfpB9Gf+HYz8a3"  # Key for decrypting Refresh Token in the database
    token_lifetime: 604800

kafka:
  brokers:
    - "re-news-kafka:29092"

swagger:
  enabled: true
  url: "/swagger"
  port: "8080"