services:
  chains-auth:
    build: .
    container_name: chains-auth
    environment:
      - KV_VIPER_FILE=./config_docker.yaml
    ports:
      - "8001:8001"
    networks:
      - chains-net

  chains-auth-postgres:
    image: postgres:15
    container_name:  chains-auth-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "7001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chains-net

volumes:
  pgdata:

networks:
  chains-net:
    external: true
