services:
  sso-oauth:
    build: .
    container_name: sso-oauth
    environment:
      - KV_VIPER_FILE=./config_docker.yaml
    ports:
      - "8001:8001"
    networks:
      - news-net

  sso-oauth-postgres:
    image: postgres:15
    container_name:  sso-oauth-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "7001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - news-net

  sso-oauth-redis:
    image: redis:6
    container_name:  sso-oauth-redis
    ports:
      - "7201:6379"
    networks:
      - news-net

volumes:
  pgdata:

networks:
  news-net:
    external: true
