openapi: 3.0.0
info:
  description: SSO REST API for Cifra app
  title: Cifra SSO REST API
  version: 0.0.1
servers:
- url: /
paths:
  /users/create:
    post:
      operationId: Test
      responses:
        "201":
          description: Created
      summary: Test
components:
  schemas:
    TokensPair:
      properties:
        data:
          $ref: '#/components/schemas/TokensPair_data'
      required:
      - data
      type: object
    RefreshToken:
      properties:
        data:
          $ref: '#/components/schemas/RefreshToken_data'
      required:
      - data
      type: object
    AccessToken:
      properties:
        data:
          $ref: '#/components/schemas/AccessToken_data'
      required:
      - data
      type: object
    Session:
      properties:
        data:
          $ref: '#/components/schemas/SessionData'
      required:
      - data
      type: object
    SessionData:
      properties:
        id:
          description: session id
          format: uuid
          type: string
        type:
          enum:
          - account_session
          type: string
        attributes:
          $ref: '#/components/schemas/SessionAttributes'
      required:
      - attributes
      - id
      - type
      type: object
    SessionAttributes:
      properties:
        account_id:
          description: user id
          format: uuid
          type: string
        client:
          description: client name and version
          type: string
        ip:
          description: IP address
          type: string
        created_at:
          description: session creation date
          format: date-time
          type: string
        last_used:
          description: last used date
          format: date-time
          type: string
      required:
      - account_id
      - client
      - created_at
      - ip
      - last_used
      type: object
    SessionsCollection:
      properties:
        data:
          $ref: '#/components/schemas/SessionsCollection_data'
      required:
      - data
      type: object
    Account:
      properties:
        data:
          $ref: '#/components/schemas/Account_data'
      required:
      - data
      type: object
    TokensPair_data_attributes:
      properties:
        access_token:
          description: Access Token
          type: string
        refresh_token:
          description: Refresh Token
          type: string
      required:
      - access_token
      - refresh_token
      type: object
    TokensPair_data:
      properties:
        type:
          enum:
          - tokens_pair
          type: string
        attributes:
          $ref: '#/components/schemas/TokensPair_data_attributes'
      required:
      - attributes
      - relationships
      - type
      type: object
    RefreshToken_data_attributes:
      properties:
        refresh_token:
          description: The refresh token to generate a new access token.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
          type: string
      required:
      - refresh_token
      type: object
    RefreshToken_data:
      properties:
        type:
          enum:
          - refresh_token
          type: string
        attributes:
          $ref: '#/components/schemas/RefreshToken_data_attributes'
      required:
      - attributes
      - type
      type: object
    AccessToken_data_attributes:
      properties:
        refresh_token:
          description: The access token to generate a new access token.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
          type: string
      required:
      - access_token
      type: object
    AccessToken_data:
      properties:
        type:
          enum:
          - access_token
          type: string
        attributes:
          $ref: '#/components/schemas/AccessToken_data_attributes'
      required:
      - attributes
      - type
      type: object
    SessionsCollection_data_attributes:
      properties:
        sessions:
          items:
            $ref: '#/components/schemas/SessionData'
          type: array
      required:
      - sessions
      type: object
    SessionsCollection_data:
      properties:
        type:
          enum:
          - account_sessions
          type: string
        attributes:
          $ref: '#/components/schemas/SessionsCollection_data_attributes'
      required:
      - attributes
      - type
      type: object
    Account_data_attributes:
      properties:
        email:
          description: Email
          type: string
        role:
          description: Role
          type: string
        created_at:
          description: Created At
          format: date-time
          type: string
        updated_at:
          description: Updated At
          format: date-time
          type: string
      required:
      - created_at
      - email
      - role
      - updated_at
      type: object
    Account_data:
      properties:
        id:
          description: Account ID
          type: string
        type:
          enum:
          - account
          type: string
        attributes:
          $ref: '#/components/schemas/Account_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
