openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra app
  version: 0.0.1
paths:
  /re-news/sso/v1/public/google/login:
    post:
      tags:
        - Login
      description: Endpoint to login use google account
      responses:
        '201':
          description: User successfully login
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/TokensPair'
        '400':
          description: One of the parameters is invalid. Refer to the response body for details.
          content:
            application/vnd.api+json:
              schema:
                description: 'Standard JSON:API error'
                type: object
                required:
                  - errors
                properties:
                  errors:
                    type: array
                    description: Non empty array of errors occurred during request processing
                    items:
                      type: object
                      required:
                        - title
                        - status
                      properties:
                        title:
                          type: string
                          description: 'Title is a short, human-readable summary of the problem'
                          example: Bad Request
                        detail:
                          type: string
                          description: Detail is a human-readable explanation specific to this occurrence of the problem
                          example: Request body was expected
                        status:
                          type: integer
                          description: Status is the HTTP status code applicable to this problem
                          example: 400
                          enum:
                            - 400
                            - 401
                            - 403
                            - 404
                            - 409
                            - 500
        '500':
          description: Internal server error
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1re-news~1sso~1v1~1public~1google~1login/post/responses/400/content/application~1vnd.api%2Bjson/schema'
components:
  schemas:
    TokensPair:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
            - relationships
          properties:
            type:
              type: string
              enum:
                - tokens_pair
            attributes:
              type: object
              required:
                - access_token
                - refresh_token
              properties:
                access_token:
                  type: string
                  description: Access Token
                refresh_token:
                  type: string
                  description: Refresh Token
    RefreshToken:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - refresh_token
            attributes:
              type: object
              required:
                - refresh_token
              properties:
                refresh_token:
                  type: string
                  description: The refresh token to generate a new access token.
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
    AccessToken:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - access_token
            attributes:
              type: object
              required:
                - access_token
              properties:
                refresh_token:
                  type: string
                  description: The access token to generate a new access token.
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
    Session:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/SessionData'
    SessionData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: session id
        type:
          type: string
          enum:
            - account_session
        attributes:
          $ref: '#/components/schemas/SessionAttributes'
    SessionAttributes:
      type: object
      required:
        - account_id
        - client
        - ip
        - created_at
        - last_used
      properties:
        account_id:
          type: string
          format: uuid
          description: account id
        client:
          type: string
          description: client name and version
        ip:
          type: string
          description: IP address
        created_at:
          type: string
          format: date-time
          description: session creation date
        last_used:
          type: string
          format: date-time
          description: last used date
    SessionsCollection:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - account_sessions
            attributes:
              type: object
              required:
                - sessions
              properties:
                sessions:
                  type: array
                  items:
                    $ref: '#/components/schemas/SessionData'
    Account:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              description: Account ID
            type:
              type: string
              enum:
                - account
            attributes:
              type: object
              required:
                - email
                - role
                - subscription
                - created_at
                - updated_at
              properties:
                email:
                  type: string
                  description: Email
                role:
                  type: string
                  description: Role
                subscription:
                  type: string
                  description: Subscription
                created_at:
                  type: string
                  format: date-time
                  description: Created At
                updated_at:
                  type: string
                  format: date-time
                  description: Updated At
