openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra app
  version: 0.0.1

paths:
  /users/create:
    post:
      summary: Test
      operationId: Test
      responses:
        '201':
          description: Created

components:
  schemas:
    TokensPair:
      $ref: './spec/components/schemas/TokensPair.yaml'
    RefreshToken:
      $ref: './spec/components/schemas/RefreshToken.yaml'
    AccessToken:
      $ref: './spec/components/schemas/AccessToken.yaml'
    Session:
      $ref: './spec/components/schemas/Session.yaml'
    SessionData:
      $ref: './spec/components/schemas/SessionData.yaml'
    SessionAttributes:
      $ref: './spec/components/schemas/SessionAttributes.yaml'
    SessionsCollection:
      $ref: './spec/components/schemas/SessionsCollection.yaml'
    Account:
      $ref: './spec/components/schemas/Account.yaml'