openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra app
  version: 0.0.1

paths:
  /re-news/chains/auth/v1/own:
    $ref: './paths/OwnAccount.yaml'

  /re-news/chains/auth/v1/own/refresh:
    $ref: './paths/Refresh.yaml'

  /re-news/chains/auth/v1/own/login:
    $ref: './paths/LoginCallback.yaml'

  /re-news/chains/auth/v1/own/logout:
    $ref: './paths/Logout.yaml'

  /re-news/chains/auth/v1/own/sessions:
    $ref: './paths/OwnSessions.yaml'

  /re-news/chains/auth/v1/own/sessions/{session_id}:
    $ref: './paths/OwnSession.yaml'

  /re-news/chains/auth/v1/admin/{account_id}:
    $ref: './paths/AdminUserAccount.yaml'

  /re-news/chains/auth/v1/admin/{account_id}/{role}:
    $ref: './paths/AdminUpdateRole.yaml'

  /re-news/chains/auth/v1/admin/{account_id}/sessions:
    $ref: './paths/AdminUserSessions.yaml'

  /re-news/chains/auth/v1/admin/{account_id}/sessions/{session_id}:
    $ref: './paths/AdminUserSession.yaml'

  #Admins

  /re-news//chains/auth/v1/own/google/login:
    $ref: './paths/LoginCallback.yaml'

  /re-news//chains/auth/v1/public/refresh:
    $ref: './paths/Refresh.yaml'

  /re-news//chains/auth/v1/public/account:
    $ref: './paths/OwnAccount.yaml'

  /re-news//chains/auth/v1/public/sessions:
    $ref: './paths/OwnSessions.yaml'

  /re-news//chains/auth/v1/public/sessions/{session_id}:
    $ref: './paths/OwnSession.yaml'

  /re-news//chains/auth/v1/private/account/{account_id}:
    $ref: './paths/AdminUserAccount.yaml'

  /re-news//chains/auth/v1/private/accounts/{account_id}/{role}:
    $ref: './paths/AdminUpdateRole.yaml'

  /re-news//chains/auth/v1/private/accounts/{account_id}/sessions:
    $ref: './paths/AdminUserSessions.yaml'

  /re-news//chains/auth/v1/private/accounts/{account_id}/sessions/{session_id}:
    $ref: './paths/AdminUserSession.yaml'


components:
  schemas:
    TokensPair:
      $ref: './spec/components/schemas/TokensPair.yaml'
    RefreshToken:
      $ref: './spec/components/schemas/RefreshToken.yaml'
    AccessToken:
      $ref: './spec/components/schemas/AccessToken.yaml'
    Session:
      $ref: './spec/components/schemas/Session.yaml'
    SessionData:
      $ref: './spec/components/schemas/SessionData.yaml'
    SessionAttributes:
      $ref: './spec/components/schemas/SessionAttributes.yaml'
    SessionsCollection:
      $ref: './spec/components/schemas/SessionsCollection.yaml'
    Account:
      $ref: './spec/components/schemas/Account.yaml'