openapi: 3.1.1
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra app
  version: 0.0.1

paths:
  /chains/auth/v1/own:
    $ref: './paths/OwnData.yaml'

  /re-news/chains/auth/v1/own/refresh:
    $ref: './paths/Refresh.yaml'

  /re-news/chains/auth/v1/own/login:
    $ref: './paths/Login.yaml'

  /re-news/chains/auth/v1/own/callback:
    $ref: './paths/LoginCallback.yaml'

  /re-news/chains/auth/v1/own/logout:
    $ref: './paths/Logout.yaml'

  /re-news/chains/auth/v1/own/sessions:
    $ref: './paths/OwnSessions.yaml'

  /re-news/chains/auth/v1/own/sessions/{session_id}:
    parameters:
      - name: session_id
        in: path
        required: true
        schema:
          type: string
    $ref: './paths/OwnSession.yaml'

    #Admins

  /re-news/chains/auth/v1/admin/{user_id}:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
    $ref: './paths/AdminGetUser.yaml'

  /re-news/chains/auth/v1/admin/{user_id}/{role}:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: role
        in: path
        required: true
        schema:
          type: string
    $ref: './paths/AdminUpdateRole.yaml'

  /re-news/chains/auth/v1/admin/{user_id}/sessions:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
    $ref: './paths/AdminUserSessions.yaml'

  /re-news/chains/auth/v1/admin/{user_id}/sessions/{session_id}:
    parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: session_id
        in: path
        required: true
        schema:
          type: string
    $ref: './paths/AdminUserSession.yaml'

components:
  schemas:
    TokensPair:
      $ref: './spec/components/schemas/TokensPair.yaml'
    RefreshToken:
      $ref: './spec/components/schemas/RefreshToken.yaml'
    AccessToken:
      $ref: './spec/components/schemas/AccessToken.yaml'
    Session:
      $ref: './spec/components/schemas/Session.yaml'
    SessionData:
      $ref: './spec/components/schemas/SessionData.yaml'
    SessionAttributes:
      $ref: './spec/components/schemas/SessionAttributes.yaml'
    SessionsCollection:
      $ref: './spec/components/schemas/SessionsCollection.yaml'
    User:
      $ref: './spec/components/schemas/User.yaml'
    Errors:
      $ref: './spec/components/schemas/Errors.yaml'

  responses:
    InvalidParameter:
      $ref: './spec/components/responses/invalidParameter.yaml'
    Unauthorized:
      $ref: './spec/components/responses/unauthorized.yaml'
    NotFound:
      $ref: './spec/components/responses/notFound.yaml'
    Forbidden:
      $ref: './spec/components/responses/forbidden.yaml'
    Internal:
      $ref: './spec/components/responses/internal.yaml'
    Conflict:
      $ref: './spec/components/responses/conflict.yaml'
    TooManyRequests:
      $ref: './spec/components/responses/tooManyRequests.yaml'
    UnsupportedMediaType:
      $ref: './spec/components/responses/unsupportedMediaType.yaml'
    InvalidPointer:
      $ref: './spec/components/responses/invalidPointer.yaml'
    InvalidQuery:
      $ref: './spec/components/responses/invalidQuery.yaml'